import 'package:flutter/material.dart';
import '../models/member.dart';
import '../services/firestore_service.dart';

class AttendanceViewModel extends ChangeNotifier {
  final FirestoreService _firestoreService = FirestoreService();

  DateTime _selectedDate = DateTime.now();
  DateTime get selectedDate => _selectedDate;

  Stream<List<Member>> get membersStream => _firestoreService.getMembers();

  Stream<List<String>> get presentMembersStream =>
      _firestoreService.getPresentMembersForDate(_selectedDate);

  void setDate(DateTime date) {
    _selectedDate = date;
    notifyListeners();
  }

  Future<void> addMember({
    required String firstName,
    required String lastName,
    required DateTime dateOfBirth,
    required String gender,
    required String phoneNumber,
  }) async {
    final newMember = Member(
      id: '', // ID will be generated by Firestore if we used .add, but let's see.
      // FirestoreService.addMember uses .add(), so ID is auto-genned.
      // The model expects an ID. For sending *to* firestore, ID is empty/ignored.
      // When reading back, we get the ID.
      firstName: firstName,
      lastName: lastName,
      dateOfBirth: dateOfBirth,
      gender: gender,
      phoneNumber: phoneNumber,
    );
    await _firestoreService.addMember(newMember);
  }

  Future<void> updateMember(Member member) async {
    await _firestoreService.updateMember(member);
    notifyListeners();
  }

  Future<void> toggleAttendance(String memberId, bool isPresent) async {
    await _firestoreService.markAttendance(_selectedDate, memberId, isPresent);
  }
}
