// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1jw7bGsfD3Njq6uMWL4pr3WKTkZ52CDQ',
    appId: '1:488127638849:web:60e2bb6eee125e56bb05c0',
    messagingSenderId: '488127638849',
    projectId: 'ludon-28493',
    authDomain: 'ludon-28493.firebaseapp.com',
    databaseURL: 'https://ludon-28493-default-rtdb.firebaseio.com',
    storageBucket: 'ludon-28493.firebasestorage.app',
    measurementId: 'G-BHECZTC0RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXUlSi-ERIUjaeIIJz5elqSNj1fT05h5c',
    appId: '1:488127638849:android:797c9c807301b412bb05c0',
    messagingSenderId: '488127638849',
    projectId: 'ludon-28493',
    databaseURL: 'https://ludon-28493-default-rtdb.firebaseio.com',
    storageBucket: 'ludon-28493.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPXX7qHTLsfQtnMbyK8ZS9NYCUo2niHbg',
    appId: '1:488127638849:ios:7964abb0c3ca65a8bb05c0',
    messagingSenderId: '488127638849',
    projectId: 'ludon-28493',
    databaseURL: 'https://ludon-28493-default-rtdb.firebaseio.com',
    storageBucket: 'ludon-28493.firebasestorage.app',
    androidClientId: '488127638849-bvh2mn6nbj30hcv4vb8ga0hnee62u6v7.apps.googleusercontent.com',
    iosClientId: '488127638849-nt09e68l5c9sp3nde0mfp5h6285i5ah3.apps.googleusercontent.com',
    iosBundleId: 'com.example.kingdomOfLightChurch',
  );
}
